export const DISPATCH_AUTH_LOGOUT_SUCCESS = 'DISPATCH_AUTH_LOGOUT_SUCCESS'
export const DISPATCH_AUTH_LOGOUT_ERROR = 'DISPATCH_AUTH_LOGOUT_ERROR'

export const FETCH_AUTH_USER_SUCCESS = 'FETCH_AUTH_USER_SUCCESS'
export const FETCH_AUTH_PROFESSIONAL_SUCCESS = 'FETCH_AUTH_PROFESSIONAL_SUCCESS'
export const FETCH_AUTH_ERROR = 'FETCH_AUTH_ERROR'

export const ADD_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS'
export const ADD_FEEDBACK_ERROR = 'ADD_FEEDBACK_ERROR'

export const UPDATE_FEEDBACK_SUCCESS = 'UPDATE_FEEDBACK_SUCCESS'
export const UPDATE_FEEDBACK_ERROR = 'UPDATE_FEEDBACK_ERROR'

export const FETCH_FEEDBACKS_SUCCESS = 'FETCH_FEEDBACKS_SUCCESS'
export const FETCH_FEEDBACKS_ERROR = 'FETCH_FEEDBACKS_ERROR'

export const ADD_ACTIVITY_SUCCESS = 'ADD_ACTIVITY_SUCCESS'
export const ADD_ACTIVITY_ERROR = 'ADD_ACTIVITY_ERROR'

export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS'
export const FETCH_EVENT_ERROR = 'FETCH_EVENT_ERROR'

export const SHOW_SPINNER = 'SHOW_SPINNER'
export const HIDE_SPINNER = 'HIDE_SPINNER'

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const FETCH_PROFESSIONAL_SUCCESS = 'FETCH_PROFESSIONAL_SUCCESS'
export const FETCH_PROFESSIONAL_ERROR = 'FETCH_PROFESSIONAL_ERROR'
