export const DISPATCH_AUTH_LOGOUT_SUCCESS = 'DISPATCH_AUTH_LOGOUT_SUCCESS'
export const DISPATCH_AUTH_LOGOUT_ERROR = 'DISPATCH_AUTH_LOGOUT_ERROR'
export const FETCH_FEEDBACKS_SUCCESS = 'FETCH_FEEDBACKS_SUCCESS'
export const FETCH_FEEDBACKS_ERROR = 'FETCH_FEEDBACKS_ERROR'
